services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: gitlab_dashboard_backend
    volumes:
      - ./backend:/app
    env_file:
      - .env
    expose:
      - "8001"
    networks:
      - app-network
    restart: unless-stopped

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: gitlab_dashboard_frontend
  #   volumes:
  #     - ./frontend:/app
  #   ports:
  #     - "8501:8501"
  #   depends_on:
  #     - backend
  #   networks:
  #     - app-network
  #   restart: unless-stopped

  frontend-react:
    build:
      context: ./frontend-react
      dockerfile: Dockerfile
    container_name: gitlab_dashboard_frontend_react
    ports:
      - "8503:80" # Exponemos el puerto 80 de Nginx al puerto 8503 de su máquina
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped
    # Para desarrollo, puede montar el volumen del código fuente:
    volumes:
      - ./frontend-react:/app
      
networks:
  app-network:
    driver: bridge