# Dockerfile.frontend
FROM python:3.11-slim
WORKDIR /app
COPY requirements_frontend.txt .
RUN pip install --no-cache-dir -r requirements_frontend.txt
COPY . .
COPY ./static ./static
# Exponemos el puerto de Streamlit
EXPOSE 11112
# El entrypoint es necesario para que Streamlit sepa cómo ejecutarse
ENTRYPOINT ["streamlit", "run", "app.py", "--server.port", "11112", "--server.address", "0.0.0.0"]