# docker-compose.yml
# SSS v4.2.0 - Configuración de Producción Base

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: gitlab_dashboard_backend
    env_file:
      - .env
    networks:
      - app-network
    depends_on:
      postgres_chatbot:
        condition: service_healthy
    restart: unless-stopped

  frontend-react:
    build:
      context: ./frontend-react
      dockerfile: Dockerfile # Usa el Dockerfile de producción por defecto
    container_name: gitlab_dashboard_frontend_react
    ports:
      - "8503:80"
    networks:
      - app-network
    depends_on:
      - backend
    restart: unless-stopped
    
  postgres_chatbot:
    image: postgres:16
    container_name: postgres_chatbot
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: